function [ D ] = spkd_v( scr, SD, qvals )

for xii=2:(size(SD,2)+1)
    for xjj=2:(size(SD,3)+1)
        scr(:,xii,xjj)= ...
            min(cat(2, ...
            scr(:,xii-1,xjj)+1, ...
            scr(:,xii,xjj-1)+1, ...
            ( ...
                scr(:,xii-1,xjj-1) ...
                + ...
                SD(:,xii-1,xjj-1) ...
            )...
            ),[],2);
    end
end
D = single(squeeze(scr(:,end,end)));

end
